---
abstract: 'A test helper providing RSPEC, Workflows, Parallelization, and Encapsulation.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.40
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fennec
provides:
  Fennec:
    file: lib/Fennec.pm
    version: 1.013
  Fennec::Finder:
    file: lib/Fennec/Finder.pm
    version: 0
  Fennec::Listener:
    file: lib/Fennec/Listener.pm
    version: 0
  Fennec::Listener::TB:
    file: lib/Fennec/Listener/TB.pm
    version: 0
  Fennec::Listener::TB2:
    file: lib/Fennec/Listener/TB2.pm
    version: 0
  Fennec::Listener::TB::Collector:
    file: lib/Fennec/Listener/TB/Collector.pm
    version: 0
  Fennec::Listener::TB::Handle:
    file: lib/Fennec/Listener/TB/Handle.pm
    version: 0
  Fennec::Listener::TB::Result:
    file: lib/Fennec/Listener/TB/Result.pm
    version: 0
  Fennec::Listener::TBWin32:
    file: lib/Fennec/Listener/TBWin32.pm
    version: 0
  Fennec::Meta:
    file: lib/Fennec/Meta.pm
    version: 0
  Fennec::Runner:
    file: lib/Fennec/Runner.pm
    version: 0
  Fennec::Util:
    file: lib/Fennec/Util.pm
    version: 0
  Test::Workflow:
    file: lib/Test/Workflow.pm
    version: 0
  Test::Workflow::Block:
    file: lib/Test/Workflow/Block.pm
    version: 0
  Test::Workflow::Layer:
    file: lib/Test/Workflow/Layer.pm
    version: 0
  Test::Workflow::Meta:
    file: lib/Test/Workflow/Meta.pm
    version: 0
  Test::Workflow::Test:
    file: lib/Test/Workflow/Test.pm
    version: 0
requires:
  Carp: 0
  Exporter::Declare: 0
  List::Util: 0
  Mock::Quick: 1.000
  Parallel::Runner: 0.013
  Scalar::Util: 0
  TAP::Parser: 0
  Test::Exception: 0.29
  Test::Simple: 0.88
  Test::Warn: 0
resources:
  bugtracker: http://github.com/exodist/Fennec/issues
  homepage: http://open-exodus.net/projects/Fennec
  license: http://dev.perl.org/licenses/
  repository: http://github.com/exodist/Fennec
version: 1.013
