---
abstract: 'A test helper providing RSPEC, Workflows, Parallelization, and Encapsulation.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fennec
provides:
  Fennec:
    file: lib/Fennec.pm
    version: 1.000_2
  Fennec::Listener:
    file: lib/Fennec/Listener.pm
  Fennec::Listener::TB:
    file: lib/Fennec/Listener/TB.pm
  Fennec::Listener::TB2:
    file: lib/Fennec/Listener/TB2.pm
  Fennec::Listener::TB::Handle:
    file: lib/Fennec/Listener/TB/Handle.pm
  Fennec::Meta:
    file: lib/Fennec/Meta.pm
  Fennec::Runner:
    file: lib/Fennec/Runner.pm
  Fennec::Util:
    file: lib/Fennec/Util.pm
  Test::Workflow:
    file: lib/Test/Workflow.pm
  Test::Workflow::Block:
    file: lib/Test/Workflow/Block.pm
  Test::Workflow::Layer:
    file: lib/Test/Workflow/Layer.pm
  Test::Workflow::Meta:
    file: lib/Test/Workflow/Meta.pm
  Test::Workflow::Test:
    file: lib/Test/Workflow/Test.pm
requires:
  Carp: 0
  Exporter::Declare: 0
  List::Util: 0
  Object::Quick: 0.012
  Parallel::Runner: 0.010
  Scalar::Util: 0
  TAP::Parser: 0
  Test::Exception: 0.29
  Test::Simple: 0.88
  Test::Warn: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.000_2
