---
abstract: 'Workflow based testing framework for Perl.'
author:
  - "Chad 'Exodist' Granum <exodist7@gmail.com>"
build_requires:
  Module::Build: 0.3601
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101831, CPAN::Meta::Converter version 2.101610'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Fennec
requires:
  Benchmark: 0
  Carp::Always: 0
  Cwd: 0
  Data::Dumper: 0
  Devel::CallerStack: 0
  Digest::MD5: 0
  Exporter::Declare: 0.016
  File::Temp: 0
  List::MoreUtils: 0
  List::Util: 0
  Parallel::Runner: 0.006
  Scalar::Util: 0
  Time::HiRes: 0
  Try::Tiny: 0
version: 0.025
